import type { Metadata } from 'next';
import './globals.css';
import { SidebarProvider } from '@/context/SidebarContext';
import { SuperProvider } from '@/context/SuperContext';

export const metadata: Metadata = {
  title: 'MewTube',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SuperProvider>
          <SidebarProvider>{children}</SidebarProvider>
        </SuperProvider>
      </body>
    </html>
  );
}
