import type { Metadata } from 'next';
import './globals.css';
import { SidebarProvider } from '@/context/SidebarContext';
import { SuperProvider } from '@/context/SuperContext';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/client/Sidebar';

export const metadata: Metadata = {
  title: 'MewTube',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SuperProvider>
          <SidebarProvider>
            <div className="flex h-screen w-screen flex-col bg-white">
              <Navbar />
              <div className="flex max-h-[calc(100%-64px)] flex-1">
                <Sidebar />
                {children}
              </div>
            </div>
          </SidebarProvider>
        </SuperProvider>
      </body>
    </html>
  );
}
